jobs:
  super-lint:
    name: Lint code base
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        DEFAULT_BRANCH: develop
        DISABLE_ERRORS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run Super-Linter
      uses: github/super-linter@v4
name: Super-Linter
on:
  repository_dispatch:
    types: trigger-ga___superlinter.yml
